### PR TITLE
MNT: Re-rendered with conda-build 3.26.1, conda-smithy 3.26.2, and co…

### PR DESCRIPTION
**Pull request by yuzie007**
…nda-forge-pinning 2023.09.26.07.13.00

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yuzie007** [comment]
Hi @awvwgk since some checks in #20 failed, I re-rendered this feedstock locally using conda-smithy. Now all checks have passed. If you kindly give a review and, if you also think reasonable, kindly merge it?

**Comment by awvwgk** [comment]
There is no update of the package here, therefore it should not be rerendered.

**Comment by yuzie007** [comment]
Thank you @awvwgk also for the reivew on this PR.

Let me comment on that, I feel it is *not unnatural* to have maintenance builds in conda-forge. We just need to increment the build number as guided in [the official document](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-recipes). As far as I read it, it is *not discouraged* to have maintenance builds, and in general I believe it is very common to do such maintenance (or refactor) in modern code developments.

The purpose of this PR was *not* updating packages, but simply because the present repository is outdated and without re-rendering all PRs will be failed (as found in #20).

If you like, I can of course re-render the feedstock *together with* some new ELPA versions. Could you kindly tell me what would you like?

**Comment by awvwgk** [comment]
I agree, however this PR would not create any change in the feedstock, since the build number was not increased. Rendering of the feedstock can be done as needed with updates to the package.

**Comment by yuzie007** [comment]
Thank you @awvwgk for your kind reply. Seeing files in my PR again, I noticed that the build number is indeed *not* automatically incremented by conda-smithy (this was my misunderstanding). Thank you for pointing it out!

I agree we can update the feedstock with new EPLA versions. I will then work on that soon.

**Pull request closed without merging**
